### ISSUE TITLE
Error on navigating docs

### ISSUE THREAD

**Issue by SimeonC** [prisma/graphql-playground#946]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
OSX 10.14.2

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.8.7

#### What is the expected behavior?
Should not crash

#### What is the actual behavior?
When navigating around the docs the UI will completely blank out - similar to #938 but the error in dev tools is different. (I'm not sure if this step relevant or it just happens after a certain period of time)

#### What steps may we take to reproduce the behavior?
* Open GraphQL Playground
* Open Docs
* Navigate around the docs for a while
* Crash happens

<details>
<summary>Error Log</summary>
```
app.d24e1768a4e1965a34d9.js:84560 RangeError: Maximum call stack size exceeded
    at seqFromValue (app.d24e1768a4e1965a34d9.js:14534)
    at Seq (app.d24e1768a4e1965a34d9.js:14203)
    at toJS (app.d24e1768a4e1965a34d9.js:18116)
    at app.d24e1768a4e1965a34d9.js:18127
    at ArraySeq.__iterate (app.d24e1768a4e1965a34d9.js:14373)
    at toJS (app.d24e1768a4e1965a34d9.js:18126)
    at app.d24e1768a4e1965a34d9.js:18121
    at ObjectSeq.__iterate (app.d24e1768a4e1965a34d9.js:14426)
    at toJS (app.d24e1768a4e1965a34d9.js:18120)
    at app.d24e1768a4e1965a34d9.js:18121
    at ObjectSeq.__iterate (app.d24e1768a4e1965a34d9.js:14426)
    at toJS (app.d24e1768a4e1965a34d9.js:18120)
    at app.d24e1768a4e1965a34d9.js:18127
    at ArraySeq.__iterate (app.d24e1768a4e1965a34d9.js:14373)
    at toJS (app.d24e1768a4e1965a34d9.js:18126)
    at app.d24e1768a4e1965a34d9.js:18121
Hg @ app.d24e1768a4e1965a34d9.js:84560
Pg.c.callback @ app.d24e1768a4e1965a34d9.js:84571
uf @ app.d24e1768a4e1965a34d9.js:84509
tf @ app.d24e1768a4e1965a34d9.js:84509
Mh @ app.d24e1768a4e1965a34d9.js:84610
Jh @ app.d24e1768a4e1965a34d9.js:84601
Kh @ app.d24e1768a4e1965a34d9.js:84600
nh @ app.d24e1768a4e1965a34d9.js:84597
Tf @ app.d24e1768a4e1965a34d9.js:84595
enqueueSetState @ app.d24e1768a4e1965a34d9.js:84515
A.setState @ app.d24e1768a4e1965a34d9.js:84323
onStateChange @ app.d24e1768a4e1965a34d9.js:12510
notify @ app.d24e1768a4e1965a34d9.js:12239
notifyNestedSubs @ app.d24e1768a4e1965a34d9.js:12278
onStateChange @ app.d24e1768a4e1965a34d9.js:12507
notify @ app.d24e1768a4e1965a34d9.js:12239
notifyNestedSubs @ app.d24e1768a4e1965a34d9.js:12278
onStateChange @ app.d24e1768a4e1965a34d9.js:12507
notify @ app.d24e1768a4e1965a34d9.js:12239
notifyNestedSubs @ app.d24e1768a4e1965a34d9.js:12278
onStateChange @ app.d24e1768a4e1965a34d9.js:12507
notify @ app.d24e1768a4e1965a34d9.js:12239
notifyNestedSubs @ app.d24e1768a4e1965a34d9.js:12278
onStateChange @ app.d24e1768a4e1965a34d9.js:12507
dispatch @ app.d24e1768a4e1965a34d9.js:47457
(anonymous) @ app.d24e1768a4e1965a34d9.js:59036
dispatch @ app.d24e1768a4e1965a34d9.js:47802
(anonymous) @ app.d24e1768a4e1965a34d9.js:39103
(anonymous) @ app.d24e1768a4e1965a34d9.js:58640
exec @ app.d24e1768a4e1965a34d9.js:72392
flush @ app.d24e1768a4e1965a34d9.js:72433
asap @ app.d24e1768a4e1965a34d9.js:72406
runPutEffect @ app.d24e1768a4e1965a34d9.js:58637
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
Promise resolved (async)
resolvePromise @ app.d24e1768a4e1965a34d9.js:58601
runEffect @ app.d24e1768a4e1965a34d9.js:58583
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
runSelectEffect @ app.d24e1768a4e1965a34d9.js:58850
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
end @ app.d24e1768a4e1965a34d9.js:58507
task.cont @ app.d24e1768a4e1965a34d9.js:58250
next @ app.d24e1768a4e1965a34d9.js:58472
currCb @ app.d24e1768a4e1965a34d9.js:58539
runSelectEffect @ app.d24e1768a4e1965a34d9.js:58850
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
runSelectEffect @ app.d24e1768a4e1965a34d9.js:58850
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
proc @ app.d24e1768a4e1965a34d9.js:58421
resolveIterator @ app.d24e1768a4e1965a34d9.js:58607
runEffect @ app.d24e1768a4e1965a34d9.js:58583
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
runSelectEffect @ app.d24e1768a4e1965a34d9.js:58850
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
proc @ app.d24e1768a4e1965a34d9.js:58421
resolveIterator @ app.d24e1768a4e1965a34d9.js:58607
runEffect @ app.d24e1768a4e1965a34d9.js:58583
next @ app.d24e1768a4e1965a34d9.js:58466
proc @ app.d24e1768a4e1965a34d9.js:58421
runForkEffect @ app.d24e1768a4e1965a34d9.js:58705
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
runCancelEffect @ app.d24e1768a4e1965a34d9.js:58744
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
takeCb @ app.d24e1768a4e1965a34d9.js:58617
put @ app.d24e1768a4e1965a34d9.js:43435
(anonymous) @ app.d24e1768a4e1965a34d9.js:43523
(anonymous) @ app.d24e1768a4e1965a34d9.js:43548
exec @ app.d24e1768a4e1965a34d9.js:72392
flush @ app.d24e1768a4e1965a34d9.js:72433
asap @ app.d24e1768a4e1965a34d9.js:72406
(anonymous) @ app.d24e1768a4e1965a34d9.js:43547
emit @ app.d24e1768a4e1965a34d9.js:43388
(anonymous) @ app.d24e1768a4e1965a34d9.js:59037
(anonymous) @ app.d24e1768a4e1965a34d9.js:13094
(anonymous) @ app.d24e1768a4e1965a34d9.js:93749
step @ app.d24e1768a4e1965a34d9.js:93552
(anonymous) @ app.d24e1768a4e1965a34d9.js:93518
fulfilled @ app.d24e1768a4e1965a34d9.js:93485
Promise resolved (async)
step @ app.d24e1768a4e1965a34d9.js:93500
(anonymous) @ app.d24e1768a4e1965a34d9.js:93502
__awaiter @ app.d24e1768a4e1965a34d9.js:93482
Playground.schemaGetter @ app.d24e1768a4e1965a34d9.js:93722
(anonymous) @ app.d24e1768a4e1965a34d9.js:93617
step @ app.d24e1768a4e1965a34d9.js:93552
(anonymous) @ app.d24e1768a4e1965a34d9.js:93518
(anonymous) @ app.d24e1768a4e1965a34d9.js:93502
__awaiter @ app.d24e1768a4e1965a34d9.js:93482
(anonymous) @ app.d24e1768a4e1965a34d9.js:93612
(anonymous) @ app.d24e1768a4e1965a34d9.js:158366
step @ app.d24e1768a4e1965a34d9.js:158327
(anonymous) @ app.d24e1768a4e1965a34d9.js:158293
(anonymous) @ app.d24e1768a4e1965a34d9.js:158277
__awaiter @ app.d24e1768a4e1965a34d9.js:158257
fn @ app.d24e1768a4e1965a34d9.js:158362
(anonymous) @ app.d24e1768a4e1965a34d9.js:158379
step @ app.d24e1768a4e1965a34d9.js:158327
(anonymous) @ app.d24e1768a4e1965a34d9.js:158293
(anonymous) @ app.d24e1768a4e1965a34d9.js:158277
__awaiter @ app.d24e1768a4e1965a34d9.js:158257
Backoff.start @ app.d24e1768a4e1965a34d9.js:158357
(anonymous) @ app.d24e1768a4e1965a34d9.js:93633
step @ app.d24e1768a4e1965a34d9.js:93552
(anonymous) @ app.d24e1768a4e1965a34d9.js:93518
(anonymous) @ app.d24e1768a4e1965a34d9.js:93502
__awaiter @ app.d24e1768a4e1965a34d9.js:93482
Playground._this.getSchema.lodash_1.debounce.trailing @ app.d24e1768a4e1965a34d9.js:93597
invokeFunc @ app.d24e1768a4e1965a34d9.js:30909
trailingEdge @ app.d24e1768a4e1965a34d9.js:30958
timerExpired @ app.d24e1768a4e1965a34d9.js:30946
setTimeout (async)
setTimeout @ app.d24e1768a4e1965a34d9.js:27222
leadingEdge @ app.d24e1768a4e1965a34d9.js:30917
debounced @ app.d24e1768a4e1965a34d9.js:30986
(anonymous) @ app.d24e1768a4e1965a34d9.js:93702
setTimeout (async)
Playground.componentWillReceiveProps @ app.d24e1768a4e1965a34d9.js:93701
Xf @ app.d24e1768a4e1965a34d9.js:84518
ug @ app.d24e1768a4e1965a34d9.js:84541
yg @ app.d24e1768a4e1965a34d9.js:84550
fh @ app.d24e1768a4e1965a34d9.js:84585
gh @ app.d24e1768a4e1965a34d9.js:84586
Jh @ app.d24e1768a4e1965a34d9.js:84601
Kh @ app.d24e1768a4e1965a34d9.js:84600
nh @ app.d24e1768a4e1965a34d9.js:84597
Tf @ app.d24e1768a4e1965a34d9.js:84595
enqueueSetState @ app.d24e1768a4e1965a34d9.js:84515
A.setState @ app.d24e1768a4e1965a34d9.js:84323
onStateChange @ app.d24e1768a4e1965a34d9.js:12510
notify @ app.d24e1768a4e1965a34d9.js:12239
notifyNestedSubs @ app.d24e1768a4e1965a34d9.js:12278
onStateChange @ app.d24e1768a4e1965a34d9.js:12507
notify @ app.d24e1768a4e1965a34d9.js:12239
notifyNestedSubs @ app.d24e1768a4e1965a34d9.js:12278
onStateChange @ app.d24e1768a4e1965a34d9.js:12507
dispatch @ app.d24e1768a4e1965a34d9.js:47457
(anonymous) @ app.d24e1768a4e1965a34d9.js:59036
dispatch @ app.d24e1768a4e1965a34d9.js:47802
(anonymous) @ app.d24e1768a4e1965a34d9.js:39103
(anonymous) @ app.d24e1768a4e1965a34d9.js:58640
exec @ app.d24e1768a4e1965a34d9.js:72392
flush @ app.d24e1768a4e1965a34d9.js:72433
asap @ app.d24e1768a4e1965a34d9.js:72406
runPutEffect @ app.d24e1768a4e1965a34d9.js:58637
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
Promise resolved (async)
resolvePromise @ app.d24e1768a4e1965a34d9.js:58601
runEffect @ app.d24e1768a4e1965a34d9.js:58583
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
end @ app.d24e1768a4e1965a34d9.js:58507
task.cont @ app.d24e1768a4e1965a34d9.js:58250
next @ app.d24e1768a4e1965a34d9.js:58472
currCb @ app.d24e1768a4e1965a34d9.js:58539
runSelectEffect @ app.d24e1768a4e1965a34d9.js:58850
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
runSelectEffect @ app.d24e1768a4e1965a34d9.js:58850
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
proc @ app.d24e1768a4e1965a34d9.js:58421
resolveIterator @ app.d24e1768a4e1965a34d9.js:58607
runEffect @ app.d24e1768a4e1965a34d9.js:58583
next @ app.d24e1768a4e1965a34d9.js:58466
proc @ app.d24e1768a4e1965a34d9.js:58421
resolveIterator @ app.d24e1768a4e1965a34d9.js:58607
runEffect @ app.d24e1768a4e1965a34d9.js:58583
next @ app.d24e1768a4e1965a34d9.js:58466
proc @ app.d24e1768a4e1965a34d9.js:58421
runForkEffect @ app.d24e1768a4e1965a34d9.js:58705
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
runCancelEffect @ app.d24e1768a4e1965a34d9.js:58744
runEffect @ app.d24e1768a4e1965a34d9.js:58586
next @ app.d24e1768a4e1965a34d9.js:58466
currCb @ app.d24e1768a4e1965a34d9.js:58539
takeCb @ app.d24e1768a4e1965a34d9.js:58617
put @ app.d24e1768a4e1965a34d9.js:43435
(anonymous) @ app.d24e1768a4e1965a34d9.js:43523
(anonymous) @ app.d24e1768a4e1965a34d9.js:43548
exec @ app.d24e1768a4e1965a34d9.js:72392
flush @ app.d24e1768a4e1965a34d9.js:72433
asap @ app.d24e1768a4e1965a34d9.js:72406
(anonymous) @ app.d24e1768a4e1965a34d9.js:43547
emit @ app.d24e1768a4e1965a34d9.js:43388
(anonymous) @ app.d24e1768a4e1965a34d9.js:59037
(anonymous) @ app.d24e1768a4e1965a34d9.js:13094
(anonymous) @ app.d24e1768a4e1965a34d9.js:151968
app.d24e1768a4e1965a34d9.js:39078 uncaught at  RangeError: Maximum call stack size exceeded
    at seqFromValue (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:14534:22)
    at Seq (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:14203:11)
    at toJS (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18116:13)
    at file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18127:17
    at ArraySeq.__iterate (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:14373:11)
    at toJS (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18126:9)
    at file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18121:21
    at ObjectSeq.__iterate (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:14426:11)
    at toJS (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18120:11)
    at file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18121:21
    at ObjectSeq.__iterate (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:14426:11)
    at toJS (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18120:11)
    at file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18127:17
    at ArraySeq.__iterate (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:14373:11)
    at toJS (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18126:9)
    at file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.d24e1768a4e1965a34d9.js:18121:21
```
</details>

![graphql playground 2019-01-29 11-13-26](https://user-images.githubusercontent.com/1085899/51879476-e97fd600-23b6-11e9-9c1c-7ca2445816eb.png)

**Comment by Huvik** [comment]
Thx for reporting this, could you please provide your schema?

**Comment by Huvik** [comment]
I think this should be fixed in the latest release. Is still a problem?

**Comment by simhnna** [comment]
this happens with the web demo. Not sure what version it is. 
1. In the demo open docs
2. Open Film query 
3. Open Film node/type
4. Open Characters
5. Open Films

repeat steps 4-5 until a crash. Usually doesn't take more than 3-5 clicks

**Comment by RobotSail** [comment]
I'm also getting this error with the following trace in console when trying to use `https://api.github.com/graphql`:
```js
app.52474f40a85b8b9c3215.js:85086 SyntaxError: Syntax Error: Expected Name, found ) (2242:3)
  2240 |     
  2241 |     last: Int
> 2242 |   ): GitActorConnection!
       |   ^
  2243 | 
  2244 |   
  2245 |   blame(
    at n (app.52474f40a85b8b9c3215.js:136036)
    at Object.parse (app.52474f40a85b8b9c3215.js:136036)
    at Object.parse$2 [as parse] (app.52474f40a85b8b9c3215.js:118729)
    at coreFormat (app.52474f40a85b8b9c3215.js:121902)
    at format (app.52474f40a85b8b9c3215.js:122079)
    at formatWithCursor (app.52474f40a85b8b9c3215.js:122091)
    at app.52474f40a85b8b9c3215.js:135986
    at Object.format (app.52474f40a85b8b9c3215.js:135994)
    at Object.prettify (app.52474f40a85b8b9c3215.js:46630)
    at Object.getSDL (app.52474f40a85b8b9c3215.js:76581)
    at SDLEditor.componentDidMount (app.52474f40a85b8b9c3215.js:155305)
    at Mh (app.52474f40a85b8b9c3215.js:85135)
    at Jh (app.52474f40a85b8b9c3215.js:85127)
    at Kh (app.52474f40a85b8b9c3215.js:85126)
    at Ph (app.52474f40a85b8b9c3215.js:85138)
    at Id (app.52474f40a85b8b9c3215.js:84992)
Hg @ app.52474f40a85b8b9c3215.js:85086
app.52474f40a85b8b9c3215.js:85086 TypeError: Cannot read property 'off' of undefined
    at SDLEditor.componentWillUnmount (app.52474f40a85b8b9c3215.js:155346)
    at Kg (app.52474f40a85b8b9c3215.js:85087)
    at Lg (app.52474f40a85b8b9c3215.js:85092)
    at Mh (app.52474f40a85b8b9c3215.js:85133)
    at Jh (app.52474f40a85b8b9c3215.js:85127)
    at Kh (app.52474f40a85b8b9c3215.js:85126)
    at Ph (app.52474f40a85b8b9c3215.js:85138)
    at Id (app.52474f40a85b8b9c3215.js:84992)
Hg @ app.52474f40a85b8b9c3215.js:85086
app.52474f40a85b8b9c3215.js:85126 Uncaught SyntaxError: Syntax Error: Expected Name, found ) (2242:3)
  2240 |     
  2241 |     last: Int
> 2242 |   ): GitActorConnection!
       |   ^
  2243 | 
  2244 |   
  2245 |   blame(
    at n (app.52474f40a85b8b9c3215.js:136036)
    at Object.parse (app.52474f40a85b8b9c3215.js:136036)
    at Object.parse$2 [as parse] (app.52474f40a85b8b9c3215.js:118729)
    at coreFormat (app.52474f40a85b8b9c3215.js:121902)
    at format (app.52474f40a85b8b9c3215.js:122079)
    at formatWithCursor (app.52474f40a85b8b9c3215.js:122091)
    at app.52474f40a85b8b9c3215.js:135986
    at Object.format (app.52474f40a85b8b9c3215.js:135994)
    at Object.prettify (app.52474f40a85b8b9c3215.js:46630)
    at Object.getSDL (app.52474f40a85b8b9c3215.js:76581)
    at SDLEditor.componentDidMount (app.52474f40a85b8b9c3215.js:155305)
    at Mh (app.52474f40a85b8b9c3215.js:85135)
    at Jh (app.52474f40a85b8b9c3215.js:85127)
    at Kh (app.52474f40a85b8b9c3215.js:85126)
    at Ph (app.52474f40a85b8b9c3215.js:85138)
    at Id (app.52474f40a85b8b9c3215.js:84992)
```
